# Preparacion de datos para los algoritmos de ML

In [47]:
import pandas as pd

In [48]:
datos_crudos = pd.read_csv('../data/housing/housing.csv')

In [49]:
# Calidad de datos
# Precision
# 1. Outliers
# 2. Inconsistencia en escalas
# 3. Valores repetidos / duplicados
# 4. Inconsistencias en los datos (tipo de dato, signo)
# Completitud
# 1. Ausentes

In [50]:
# Completitud: Manejo de valores ausentes

datos_crudos.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [51]:
datos_crudos[datos_crudos['total_bedrooms'].isna()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
182,-118.27,34.04,13.0,1784.0,NaN,2158.0,682.0,1.7038,118100.0,<1H OCEAN
327,-117.65,34.04,15.0,3393.0,NaN,2039.0,611.0,3.9336,151000.0,INLAND
366,-122.50,37.75,44.0,1819.0,NaN,1137.0,354.0,3.4919,271800.0,NEAR OCEAN
477,-117.99,34.14,30.0,2346.0,NaN,1988.0,474.0,2.5625,153000.0,INLAND
495,-114.59,34.83,41.0,812.0,NaN,375.0,158.0,1.7083,48500.0,INLAND
...,...,...,...,...,...,...,...,...,...,...
19880,-118.23,33.94,36.0,1110.0,NaN,1417.0,302.0,2.3333,92100.0,<1H OCEAN
19952,-119.19,34.20,18.0,3620.0,NaN,3171.0,779.0,3.3409,220500.0,NEAR OCEAN
20088,-119.73,36.83,8.0,3602.0,NaN,1959.0,580.0,5.3478,138800.0,INLAND
20325,-118.88,34.17,15.0,4260.0,NaN,1701.0,669.0,5.1033,410700.0,<1H OCEAN
20345,-122.22,38.15,7.0,5129.0,NaN,2824.0,738.0,5.5138,171100.0,NEAR BAY

In [52]:
# Hacer un EDA de los datos ausentes

In [53]:
# 1. Borrar las filas
# 2. Borrar la columna
# 3. Imputar

In [54]:
metricas_datos_ausentes = datos_crudos.isna().sum().reset_index()

In [55]:
metricas_datos_ausentes.columns = ['nombre_columna', 'total_ausentes']

In [56]:
metricas_datos_ausentes['%_total'] = metricas_datos_ausentes['total_ausentes'] / datos_crudos.shape[0]

In [57]:
datos_crudos.shape

(20640, 10)

In [58]:
metricas_datos_ausentes

       nombre_columna  total_ausentes   %_total
0           longitude               0  0.000000
1            latitude               0  0.000000
2  housing_median_age               0  0.000000
3         total_rooms               0  0.000000
4      total_bedrooms             207  0.010029
5          population               0  0.000000
6          households               0  0.000000
7       median_income               0  0.000000
8  median_house_value               0  0.000000
9     ocean_proximity               0  0.000000

In [59]:
datos_limpios = datos_crudos.copy()

In [60]:
datos_limpios.dropna(subset=['total_bedrooms'], inplace=True) # Opcion: borrar filas ausentes

In [61]:
datos_limpios.drop('total_bedrooms', axis=1) # Opcion: borrar columna

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,1387.0,530.0,2.3886,89400.0,INLAND

In [62]:
datos_limpios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.7+ MB

In [63]:
datos_limpios.reset_index(inplace=True, drop=True)

In [64]:
datos_limpios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20433 entries, 0 to 20432
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [65]:
datos_limpios_imputados = datos_crudos.copy()

# Tipos de clase en SKLEARN
## Estimador -> fit()
## Transformador -> transform() transforma los datos
## Predictor -> predict()

In [66]:
from sklearn.impute import SimpleImputer
import numpy as np

# Mediana, Media -> No pueden ser usados en varias de texto!!!

imputador = SimpleImputer(strategy='median')

# Seleccionar Filas numericas

data_pre_imputacion = datos_limpios_imputados.select_dtypes(include=[np.number])

imputador.fit(data_pre_imputacion)

# .fit_transform()

SimpleImputer(strategy='median')

In [67]:
datos_limpios_imputados = imputador.transform(data_pre_imputacion)

In [68]:
imputador.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'], dtype=object)

In [69]:
type(datos_limpios_imputados)

numpy.ndarray

In [70]:
datos_limpios_imputados = pd.DataFrame(datos_limpios_imputados, 
                            columns=data_pre_imputacion.columns,
                            index=data_pre_imputacion.index)

In [71]:
datos_limpios_imputados.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [72]:
imputador.strategy

'median'

In [73]:
# Outliers

In [74]:
# Filtrar los outliers por 3*std o > Q3 + 1.5*IQR O < Q1 - 1.5IQR

# Identificar los atipicos con un predictor 'inteligente'

In [75]:
from sklearn.ensemble import IsolationForest

isolation_forest = IsolationForest(random_state=123)

datos_limpios_numericos = datos_limpios.select_dtypes(include=[np.number])

prediccion_atipicos = isolation_forest.fit_predict(datos_limpios_numericos)

In [76]:
prediccion_atipicos

array([-1, -1, -1, ...,  1,  1,  1])

In [77]:
#datos_limpios = datos_limpios.iloc[prediccion_atipicos == 1]

In [78]:
#datos_limpios.info()

In [79]:
datos_limpios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20433 entries, 0 to 20432
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [80]:
# Manejo de variables de texto -> Categoricas

In [81]:
datos_limpios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20433 entries, 0 to 20432
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [82]:
datos_cat = datos_limpios[['ocean_proximity']]

In [83]:
type(datos_cat)

pandas.core.frame.DataFrame

In [84]:
datos_cat.value_counts()

ocean_proximity
<1H OCEAN          9034
INLAND             6496
NEAR OCEAN         2628
NEAR BAY           2270
ISLAND                5
Name: count, dtype: int64

In [85]:
# Encoding -> Texto a Numeros
# Nominal: sin orden
# Ordinal: con orden

In [86]:
from sklearn.preprocessing import OrdinalEncoder

codificador_ordinal = OrdinalEncoder()

datos_cat_cod = codificador_ordinal.fit_transform(datos_cat)

In [87]:
datos_cat_cod

array([[3.],
       [3.],
       [3.],
       ...,
       [1.],
       [1.],
       [1.]])

In [88]:
codificador_ordinal.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [89]:
datos_limpios

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20428,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20429,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20430,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20431,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20432,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [91]:
datos_limpios_nominal = pd.get_dummies(datos_limpios, drop_first=True)

In [93]:
datos_limpios['ocean_proximity_ordinal'] = datos_cat_cod

In [95]:
datos_limpios['ocean_proximity_ordinal'] = datos_limpios['ocean_proximity_ordinal'].astype(int)

In [ ]:
# Feature Scaling:
# Normalizacion -> rango fijo = [-1,1]
# Estandarizacion -> normal: media=0 y std=1

In [96]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [97]:
min_max = MinMaxScaler(feature_range=(-1,1))
standard = StandardScaler()

In [101]:
datos_limpios.drop(columns=['ocean_proximity'], inplace=True)

In [103]:
norm_scaling_features = min_max.fit_transform(datos_limpios)
stand_scaling_features = standard.fit_transform(datos_limpios)

In [ ]:
# TO-DO:
# Comparar distribuciones de cada escalamiento con las originales
# Hacer una tuberia para cada datasets de entrenamiento

In [105]:
from sklearn.pipeline import Pipeline

tuberia_transformacion = Pipeline([
    ('imputacion', SimpleImputer(strategy='median')),
    ('estandarizar', StandardScaler())
])

In [ ]:
tuberia_transformacion.fit_transform()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_valid_caract, test_caract, train_valid_obj, test_obj = train_test_split(caracteristica, objetivo, test_size=0.20)
train_carac, valid_carac, train_obj, valid_obj = train_test_split(train_valid_caract, train_valid_obj, test_size=0.2)