# Preparacion de datos para los algoritmos de ML

In [1]:
import pandas as pd

In [2]:
datos_crudos = pd.read_csv('../data/housing/housing.csv')

In [3]:
# Calidad de datos
# Precision
# 1. Outliers
# 2. Inconsistencia en escalas
# 3. Valores repetidos / duplicados
# 4. Inconsistencias en los datos (tipo de dato, signo)
# Completitud
# 1. Ausentes

In [4]:
# Completitud: Manejo de valores ausentes

datos_crudos.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [5]:
datos_crudos[datos_crudos['total_bedrooms'].isna()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
182,-118.27,34.04,13.0,1784.0,NaN,2158.0,682.0,1.7038,118100.0,<1H OCEAN
327,-117.65,34.04,15.0,3393.0,NaN,2039.0,611.0,3.9336,151000.0,INLAND
366,-122.50,37.75,44.0,1819.0,NaN,1137.0,354.0,3.4919,271800.0,NEAR OCEAN
477,-117.99,34.14,30.0,2346.0,NaN,1988.0,474.0,2.5625,153000.0,INLAND
495,-114.59,34.83,41.0,812.0,NaN,375.0,158.0,1.7083,48500.0,INLAND
...,...,...,...,...,...,...,...,...,...,...
19880,-118.23,33.94,36.0,1110.0,NaN,1417.0,302.0,2.3333,92100.0,<1H OCEAN
19952,-119.19,34.20,18.0,3620.0,NaN,3171.0,779.0,3.3409,220500.0,NEAR OCEAN
20088,-119.73,36.83,8.0,3602.0,NaN,1959.0,580.0,5.3478,138800.0,INLAND
20325,-118.88,34.17,15.0,4260.0,NaN,1701.0,669.0,5.1033,410700.0,<1H OCEAN
20345,-122.22,38.15,7.0,5129.0,NaN,2824.0,738.0,5.5138,171100.0,NEAR BAY

In [6]:
# Hacer un EDA de los datos ausentes

In [7]:
# 1. Borrar las filas
# 2. Borrar la columna
# 3. Imputar

In [8]:
metricas_datos_ausentes = datos_crudos.isna().sum().reset_index()

In [9]:
metricas_datos_ausentes.columns = ['nombre_columna', 'total_ausentes']

In [10]:
metricas_datos_ausentes['%_total'] = metricas_datos_ausentes['total_ausentes'] / datos_crudos.shape[0]

In [11]:
datos_crudos.shape

(20640, 10)

In [12]:
metricas_datos_ausentes

       nombre_columna  total_ausentes   %_total
0           longitude               0  0.000000
1            latitude               0  0.000000
2  housing_median_age               0  0.000000
3         total_rooms               0  0.000000
4      total_bedrooms             207  0.010029
5          population               0  0.000000
6          households               0  0.000000
7       median_income               0  0.000000
8  median_house_value               0  0.000000
9     ocean_proximity               0  0.000000

In [13]:
datos_limpios = datos_crudos.copy()

In [14]:
datos_limpios.dropna(subset=['total_bedrooms'], inplace=True) # Opcion: borrar filas ausentes

In [15]:
datos_limpios.drop('total_bedrooms', axis=1) # Opcion: borrar columna

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,1387.0,530.0,2.3886,89400.0,INLAND

In [16]:
datos_limpios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.7+ MB

In [17]:
datos_limpios.reset_index(inplace=True, drop=True)

In [18]:
datos_limpios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20433 entries, 0 to 20432
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [19]:
datos_limpios_imputados = datos_crudos.copy()

# Tipos de clase en SKLEARN
## Estimador -> fit()
## Transformador -> transform() transforma los datos
## Predictor -> predict()

In [20]:
from sklearn.impute import SimpleImputer
import numpy as np

# Mediana, Media -> No pueden ser usados en varias de texto!!!

imputador = SimpleImputer(strategy='median')

# Seleccionar Filas numericas

data_pre_imputacion = datos_limpios_imputados.select_dtypes(include=[np.number])

imputador.fit(data_pre_imputacion)

# .fit_transform()

SimpleImputer(strategy='median')

In [21]:
datos_limpios_imputados = imputador.transform(data_pre_imputacion)

In [22]:
imputador.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'], dtype=object)

In [23]:
type(datos_limpios_imputados)

numpy.ndarray

In [24]:
datos_limpios_imputados = pd.DataFrame(datos_limpios_imputados, 
                            columns=data_pre_imputacion.columns,
                            index=data_pre_imputacion.index)

In [25]:
datos_limpios_imputados.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [26]:
imputador.strategy

'median'

In [27]:
# Outliers

In [28]:
# Filtrar los outliers por 3*std o > Q3 + 1.5*IQR O < Q1 - 1.5IQR

# Identificar los atipicos con un predictor 'inteligente'

In [29]:
from sklearn.ensemble import IsolationForest

isolation_forest = IsolationForest(random_state=123)

datos_limpios_numericos = datos_limpios.select_dtypes(include=[np.number])

prediccion_atipicos = isolation_forest.fit_predict(datos_limpios_numericos)

In [30]:
prediccion_atipicos

array([-1, -1, -1, ...,  1,  1,  1])

In [31]:
#datos_limpios = datos_limpios.iloc[prediccion_atipicos == 1]

In [32]:
#datos_limpios.info()

In [33]:
datos_limpios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20433 entries, 0 to 20432
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [34]:
# Manejo de variables de texto -> Categoricas

In [35]:
datos_limpios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20433 entries, 0 to 20432
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [36]:
datos_cat = datos_limpios[['ocean_proximity']]

In [37]:
type(datos_cat)

pandas.core.frame.DataFrame

In [38]:
datos_cat.value_counts()

ocean_proximity
<1H OCEAN          9034
INLAND             6496
NEAR OCEAN         2628
NEAR BAY           2270
ISLAND                5
Name: count, dtype: int64

In [39]:
# Encoding -> Texto a Numeros
# Nominal: sin orden
# Ordinal: con orden

In [40]:
from sklearn.preprocessing import OrdinalEncoder

codificador_ordinal = OrdinalEncoder()

datos_cat_cod = codificador_ordinal.fit_transform(datos_cat)

In [41]:
datos_cat_cod

array([[3.],
       [3.],
       [3.],
       ...,
       [1.],
       [1.],
       [1.]])

In [42]:
codificador_ordinal.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [43]:
datos_limpios

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20428,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20429,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20430,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20431,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20432,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [44]:
datos_limpios_nominal = pd.get_dummies(datos_limpios, drop_first=True)

In [45]:
datos_limpios['ocean_proximity_ordinal'] = datos_cat_cod

In [46]:
datos_limpios['ocean_proximity_ordinal'] = datos_limpios['ocean_proximity_ordinal'].astype(int)

In [47]:
# Feature Scaling:
# Normalizacion -> rango fijo = [-1,1]
# Estandarizacion -> normal: media=0 y std=1

In [48]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [49]:
min_max = MinMaxScaler(feature_range=(-1,1))
standard = StandardScaler()

In [50]:
datos_limpios.drop(columns=['ocean_proximity'], inplace=True)

In [51]:
norm_scaling_features = min_max.fit_transform(datos_limpios)
stand_scaling_features = standard.fit_transform(datos_limpios)

In [52]:
# TO-DO:
# Comparar distribuciones de cada escalamiento con las originales
# Hacer una tuberia para cada datasets de entrenamiento

In [53]:
from sklearn.pipeline import Pipeline

tuberia_transformacion = Pipeline([
    ('imputacion', SimpleImputer(strategy='median')),
#   Ordinal encoder
    ('estandarizar', StandardScaler())
])

In [54]:
datos_limpios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20433 entries, 0 to 20432
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   longitude                20433 non-null  float64
 1   latitude                 20433 non-null  float64
 2   housing_median_age       20433 non-null  float64
 3   total_rooms              20433 non-null  float64
 4   total_bedrooms           20433 non-null  float64
 5   population               20433 non-null  float64
 6   households               20433 non-null  float64
 7   median_income            20433 non-null  float64
 8   median_house_value       20433 non-null  float64
 9   ocean_proximity_ordinal  20433 non-null  int64
dtypes: float64(9), int64(1)
memory usage: 1.6 MB

In [62]:
datos_transformados = tuberia_transformacion.fit_transform(datos_limpios)

In [63]:
datos_transformados = pd.DataFrame(datos_transformados, columns=datos_limpios.columns)

In [65]:
datos_transformados.to_csv('../data/clean/hosing_transformed.csv')

In [ ]:
# Transformadores Personalizados

In [67]:
datos_crudos.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [68]:
datos_crudos.duplicated().sum()

0

In [69]:
datos_crudos_sin_ausentes = datos_crudos.dropna()

In [71]:
num_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('standarize', StandardScaler())
])

In [72]:
from sklearn.preprocessing import OneHotEncoder

In [73]:
cat_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

In [81]:
from sklearn.compose import ColumnTransformer, make_column_selector

In [76]:
datos_crudos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [77]:
columnas_numericas = ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value']

In [78]:
columnas_categoricas = ['ocean_proximity']

In [82]:
preprocessing = ColumnTransformer([
    ('num', num_pipeline, make_column_selector(dtype_include=np.number)),
    ('cat', cat_pipeline, make_column_selector(dtype_include=object))
])

In [85]:
dataset_final = preprocessing.fit_transform(datos_crudos)

dataset_final = pd.DataFrame(dataset_final, columns=preprocessing.get_feature_names_out())

In [86]:
dataset_final.head()

,num__longitude,num__latitude,num__housing_median_age,num__total_rooms,num__total_bedrooms,num__population,num__households,num__median_income,num__median_house_value,cat__ocean_proximity_<1H OCEAN,cat__ocean_proximity_INLAND,cat__ocean_proximity_ISLAND,cat__ocean_proximity_NEAR BAY,cat__ocean_proximity_NEAR OCEAN
0,-1.327835,1.052548,0.982143,-0.804819,-0.972476,-0.974429,-0.977033,2.344766,2.129631,0.0,0.0,0.0,1.0,0.0
1,-1.322844,1.043185,-0.607019,2.045890,1.357143,0.861439,1.669961,2.332238,1.314156,0.0,0.0,0.0,1.0,0.0
2,-1.332827,1.038503,1.856182,-0.535746,-0.827024,-0.820777,-0.843637,1.782699,1.258693,0.0,0.0,0.0,1.0,0.0
3,-1.337818,1.038503,1.856182,-0.624215,-0.719723,-0.766028,-0.733781,0.932968,1.165100,0.0,0.0,0.0,1.0,0.0
4,-1.337818,1.038503,1.856182,-0.462404,-0.612423,-0.759847,-0.629157,-0.012881,1.172900,0.0,0.0,0.0,1.0,0.0

In [88]:
dataset_final.to_csv('../data/clean/hosing_transformed_full_pipeline.csv', index=False)